[build-system]
requires = [
    "scikit-build-core>=0.8.0",
    "cmake>=3.15",
    "ninja",
    "cython>=3.0.0",
    "numpy>=1.21.0",
    "setuptools>=61.0.0"
]
build-backend = "scikit_build_core.build"

[project]
name = "optv"
version = "0.3.0"
description = "OpenPTV Python bindings"
readme = "README.txt"
requires-python = ">=3.10"
license = "LGPL-3.0-or-later"
authors = [
    {name = "OpenPTV Community", email = "openptv@googlegroups.com"}
]
dependencies = [
    "numpy>=1.21.0",
    "pyyaml",
]

[tool.scikit-build]
cmake.version = ">=3.15"  # Fixed: Added version specifier
cmake.source-dir = "../liboptv"
cmake.build-type = "Release"
wheel.packages = ["optv"]
wheel.expand-macos-universal-tags = true

[tool.setuptools]
packages = ["optv"]
package-dir = {"optv" = "optv"}
