[build-system]
requires = ["setuptools", "wheel", "cibuildwheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*"]

before-build = [
    "pip install numpy",
    "pip install cython",
    "python setup.py prepare",
    "python setup.py build_ext --inplace",
    "cd ../"
]

windows = ["cp310-*", "cp311-*", "cp312-*", "cp313-*"]
manylinux-x86_64-image = "manylinux2014"
macos = ["cp310-*", "cp311-*", "cp312-*", "cp313-*"]


# Run tests after building the wheel
test-command = "pytest {project}/tests"

[[tool.cibuildwheel.overrides]]
select = "cp3{8,9}-*"
manylinux-x86_64-image = "manylinux2010"
