name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        with: 
          package_dir: py_bind

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with: 
          package_dir: py_bind

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.4.0

      - name: Build wheels
        run: python -m cibuildwheel py_bind --output-dir py_bind/wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: py_bind/wheelhouse/*.whl
